# Run linting actions to check for trailing whitespace and
# commit message issues.
name: Linter/commit check

on:
  push:
  workflow_dispatch:
jobs:
  linters:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0